version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: leafgrow_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    ports:
      - "5432:5432"

  app:
    image: leafgrow-spring-boot-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/leafgrow_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty007
