spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/leafgrow_project
    username: postgres
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: postgres
#    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        ddl-auto: create-drop
  mail:
    username: leafgrow.project@gmail.com
    password: yhwnykriinuapexe
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

key:
  access: vCzzRbdnRQnZaz0yMft6CM6XOFxH5RFXlEp2SfJaENg=
  refresh: w4nW81yrLjMg5OEIoiZEiGSHCOgZJwqadOF2Y3LhSUQ=
