<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LeafGrow.de: Aktivieren Sie nun Ihr Kundenkonto</title>
</head>
<body>
<h1 style="color: green">Bestätigung der Anmeldung</h1>
<h2>Hallo, ${name}!</h2>
<p>Um dein Kundenkonto jetzt zu aktivieren, klick bitte auf folgenden <a href="${link}"> Link</a>.</p>
<br>
<p>Mit freundlichen Grüßen</p>
<p>Dein LeafGrow Support-Team</p>
</body>
</html>